services:
  ovh-exporter:
    image: ghcr.io/wiremind/ovh-exporter
    build:
      context: .
    container_name: ovh-exporter
    ports:
      - "8080:8080"
    environment:
      OVH_ENDPOINT: "ovh-eu"
      OVH_APP_KEY: ""
      OVH_APP_SECRET: ""
      OVH_CONSUMER_KEY: ""
      OVH_CLOUD_PROJECT_INSTANCE_BILLING_PROJECT_IDS: ""
      OVH_CACHE_UPDATE_INTERVAL: "300"
      SERVER_PORT: "8080"
