services:
  ovh-exporter:
    image: ghcr.io/wiremind/ovh-exporter
    build:
      context: .
      dockerfile: Containerfile
    container_name: ovh-exporter
    ports:
      - "8080:8080"
    env_file: "ovh-exporter.env"
